name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: /jpemberton1-chwy/github-actions-test
          ref: master
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
      - name: Check status of the ref
        run: git status
