name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: /jpemberton1-chwy/github-actions-test
          ref: master
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
      - name: Telling Git who I am
        run: |
          git config --global user.email "octokat@octokat.com"
          git config --global user.name "Octokat"
      - name: Initializing a Git repo
        run: git init .
      - name: Checking status
        run: git status
      - name: Setting remote
        run: git remote add origin jpemberton1-chwy/github-actions-test.git
      - name: Adding something to the end of README
        run: echo "It was the best of times." >> README.md
      - name: Switching branches
        run: git checkout -b automate/update-readme
      - name: Committing to the repo
        run: |
          git add -A
          git commit -a -m "Updating README"
      - name: Pushing to the repo
        run: git -c http.extraheader="AUTHORIZATION: basic ${{ secrets.PAT }}" push --set-upstream origin automate/update-readme
